### ISSUE TITLE
Fallschirm um wieder auf FS des Picos zu zugreifen

### ISSUE THREAD

**Issue by ullisun** [TGD-Consulting/PiMowBot-RC#1]
Ich habe festgestellt, dass ein umbenennen der main.py auch über programmcode möglich ist.
Hierzu habe ich  in meinem Pico Code, eine art setup Routine eingebaut, die für ca 5 Sec. Durchlaufen wird.
hier mein Code dazu

def check_rename():
    try:
        os.stat("main.py")
        log('"Info":"benenne main.py in main_1.py um"')
        os.rename("main.py","main_1.py")
        machine.reset()
        return True
    except OSError:
        print("Datei ist nicht da")
        log('"INFO":"keine main.py vorhanden"')
        return False

def run_setup():
    start=time.ticks_ms()
    while time.ticks_ms()-start <=5000:
        if ADMIN.value()==0:     # Taster der an PIN 28 des Picos angeschlossen ist
            if check_rename():
                break
        time.sleep(0.1)
        ledrot.toggle()

**Comment by TGD-Consulting** [comment]
@ullisun: Der Fallschirm ist nun bei RCjoy.py implementiert. Er wird bei 2-maligen drücken des Buttons nach dem PowerUp des Pico ausgelöst. Beim RControl.py wird das mit der nächsten Version ergänzt.
